### PR TITLE
feat: update Observed PM2.5 sensor data

### LINKED ISSUE #148: Add Microsoft Sensor reading aggregate to map

### PR DESCRIPTION
**Pull request by bodom0015**
## Problem
Observed Particulate Matter (PM2.5) data needs to be updated

Fixes #148 

## Approach
* feat: use new data + metadata links from @jluiuc to display this data in the ChiVes frontend
* fix: update "Source Data" CSV file to use more recent readings
* fix: restore/rename overlay to "Microsoft PM2.5 Readings" - these are historical sensor readings that may or may not match current color values on the map
* fix: use new color scheme (YlOrBr w/ 8 bins) for all Air Quality indicators + Source Data toggle

Screenshot 2024-07-29 at 10 49 09 AM

## How to Test
1. Navigate to https://deploy-preview-152--chicago-env-explorer.netlify.app/map
2. From the Variables dropdown, select "Observed Particulate Matter (PM2.5)" from the Air Quality category
    * You should see the data is displayed in the map to the right
    * You should see some overlayed sensor readings appear in the map (do these values need to be updated as well?)
    * You should see some additional controls in the panel, such as "2D or 3D" and "Aggregated by Tract or Source Data"
3. Toggle from "Aggregated by Tract" to "Source Data"
    * You should see that different values now appear in the map
4. Toggle from 2D to 3D
    * You should see the perspective shift slightly to show a 3D rendering of this data on the map

### CODE REVIEW

**Comment by jluiuc** [comment]
It looks like the overlaid sensor readings are from the old data, as they contain values higher than the new data's highest value.  Also, I noticed the legend properly shows the true min and max at each end, but in between the value do not match this.

**Review by jluiuc — COMMENTED** [review]
It looks like the overlaid sensor readings are from the old data, as they contain values higher than the new data's highest value.  Also, while the Aggregated by Tract/Source Data button works, I'm not sure what the differences are from, as I only submitted values aggregated to each tract. Perhaps this is also from the old data? I also noticed the legend properly shows the true min and max at each end, but in between the values do not match this (but the min and max are definitely correct).

**Comment by bodom0015** [comment]
Hey, @jluiuc! Thank you for bringing these issues up, and sorry for overlooking them in my first attempt :pray:

I removed the old/hardcoded bins - this should fix the Legend at the bottom to display quantile bins :+1:
@mradamcox and I are looking into the toggle for "Aggregated vs Source Data" as well as the "Weekly PM2.5" overlay, since they both appear to be using old sensor data as you mentioned. We've tracked down the PM2.5 overlay values to an archived process [here](https://github.com/healthyregions/air-quality-idw). I don't have direct access to the S3 bucket here, so we're trying to figure out the best way to update this data going forward 🤔

**Comment by jluiuc** [comment]
Great, the legend looks good now! Also, I have the raster from the initial interpolation before aggregating to tracts. Maybe that is what the Aggregated vs Source Data button did? I'm also thinking the number overlays might correlate to each sensor from the previous data. I also have the reading averages and lat/long for each sensor if that is desired.

**Comment by bodom0015** [comment]
Per @Makosak I've updated the bins + color scale so that they mostly match the other Air Quality variables, despite the differing number of bins:
Screenshot 2024-04-23 at 11 50 45 AM

@jluiuc let me know if there's any other information I can provide that might help with updating the "Source Data" toggle and/or the overlayed sensor values :smile:

**Comment by Makosak** [comment]
Updated the bins for this map using Viridis 6 bin formula --
Screen Shot 2024-06-28 at 4 55 27 PM

We will also need to remove the text "Data from to" as no longer relevant. 
Screen Shot 2024-06-28 at 4 57 04 PM

**Comment by Makosak** [comment]
@jluiuc would you still have the CSV with aggregated measures by _sensor__? This was the final piece needed for this!

**Comment by jluiuc** [comment]
I do! I've just sent an email with it attached

**Comment by bodom0015** [comment]
Updated all AQ variables to have the same number of bins (8), and to use the new color scheme that was discussed via email: [YlOrBr](https://colorbrewer2.org/#type=sequential&scheme=YlOrBr&n=8)
Screenshot 2024-07-29 at 10 49 09 AM

I made sure the "Source Data" toggle uses this new color scheme as well :+1:
Screenshot 2024-07-29 at 10 49 37 AM

Note that the "Microsoft PM2.5 Readings" are historical data, and may not match the current color values being displayed on the map

**Review by mradamcox — APPROVED** [review]
Finally got time to check this out and handle the merge conflicts. Happy to merge it now. I made a few extra changes 1) Removed the "Data from .. to .." text which has been obsolete for a long time now, and 2) updated the labels overlay to read from the new data, and 3) actually styled the extrusion heights to reflect the values... apparently this was never done before, and I'm not sure why...
image

**Pull request merged**
