### PR TITLE
Updated About Page

### PR DESCRIPTION
**Pull request by Makosak**
Including multiple long-stranding updates including:
- updated community members in contrib & team sections,
- inclusion of citation and Zenodo DOI,
- revised introduction & contrib sections to read with greater clarity,
- update staff in new 'active' and 'past' project teams.

Ready for review to improve further. Will likely have final tweaks after full team & partner review (including additional community members, team photos and updated links, etc).

### CODE REVIEW

**Comment by mradamcox** [comment]
@Makosak Looks good, though I fixed up some of the HTML style just for regularity. We'll have to wait to deploy this though until the data changes described in #158 are completed, because if we rebuild the production site now it would include some broken column names.

**Review by mradamcox — APPROVED** [review]
(see above comment)

**Comment by Makosak** [comment]
added some minor fixes, new resource for guide

**Comment by Makosak** [comment]
#128 linked

**Pull request merged**
