### PR TITLE
feat: add Public Housing overlay + dynamically read overlay data from Google Sheets

### LINKED ISSUE #145: Add public housing as new layer
Requested by PRN Collaboration.

+ Include all CHA housing, categorize by type (ex. senior housing)
+ Develop as a Google Sheet, Lonette & PRN staff would update and manage long-term
+ Add as a new layer/overlay

### LINKED ISSUE #168: Adding Affordable Housing Units as Data Overlay
Via People's Response Network request; interest in adding a public housing layer to help identify areas vulnerable to heat impact.

I found this dataset on the City Data Portal we could link using their API endpoint/JSON: 
- https://data.cityofchicago.org/Community-Economic-Development/Affordable-Rental-Housing-Developments/s6ha-ppgi/about_data
- https://data.cityofchicago.org/resource/s6ha-ppgi.json

Let's use the "property type" column to visualize different color categories, using a qualitative color palette like: https://colorbrewer2.org/#type=qualitative&scheme=Paired&n=9

### LINKED ISSUE #173: Create (and document) new Resource Overlays sheet
As we are adding more layers to the map that don't fit the original design, like locations of cooling centers and public housing, we should improve the way we store and configure those types of layers. Currently, a lot of this is hard-coded, so we need to abstract it out to a new sheet that defines each layer. Ultimately, I think we can continue to use the existing "Data Overlay" dropdown on the frontend (@Makosak to confirm this?), but we need to pull this list from a location outside of the codebase, and we also need to display a bit more information for each layer. Here's what I'm thinking we'll need to get this going,

- New google sheet, Data Overlays, with the following fields:
    - Display Name: name that shows up in the dropdown.
    - Description: description which will have to be added somewhere in the frontend.
    - Data Source: for now, this will be the name of a GeoJSON file that is stored in `/geojson/` (this is where these files are already stored)
    - Geometry Type: This will be `point` or `polygon` (we don't have any line layers at this time)
    - Symbol Prop: (optional) Name of the property on each feature that has the value needed to determine the symbol color.
    - Fill Color: (optional)
        - If no Symbol Prop is provided, this can be a single color
        - If a Symbol Prop is provided, this value should be modeled after the existing color scales for these layers. For example (redlining):
        ```
        {
            A: [115, 169, 77],
            B: [52, 172, 198],
            C: [219, 207, 0],
            D: [226, 77, 90],
        }
        ```
        - If no Fill Color is provided, there will be no fill on the symbol (necessary for a layer with only outlines, like the neighborhood layer
    - Line Color: (optional)
        - If a Line Color is provided, use it for the outline of a point/circle, or for the outline of a polygon
    - Line Width: (optional)
        - Only draw an outline on a polygon or circle/point if a Line Width is provided

This symbolizing can get complicated pretty quick, but I think we'll need all of this information (at least) just to replicate what we already have on the map.

Once this sheet is created with one or two test layers, it should be built and loaded alongside other sheets like columns.json and used to populate the `overlayLayers` list in MapSection.js.

Keep in mind, I'm sure we'll still need to handle some exceptional layers, so it's fine if something needs to be appended to that list for now.

### PR DESCRIPTION
**Pull request by bodom0015**
## Problem
We would like to add an overlay showing locations of Public Housing in Chicago (fixes #145, fixes #168)

We would also like an easier pattern for adding these overlays to the ChiVes frontend (fixes #173)

## Approach
* feat: create a new sheet for Overlays in our Variables spreadsheet, read/fetch these during the `yarn build:data` step to create `src/config/overlays.json`
    * Point data is read as CSV and parsed into GeoJSON format
    * Polygon data is read directly from GitHub (via URL at runtime) in GeoJSON format
* feat: at runtime read `overlays.json` and use this to render our list of possible overlays, show enabled overlays on the map
* fix: migrate all existing overlays to use this new pattern (order of overlays in the UI is determined by the order of the rows within the Google Sheet)

~~NOTE 1: currently only "Cooling Centers" + "Public Housing" (point data) are read using this pattern - more discovery is needed to determine the desired CSV format when `geometryType === 'polygon'`~~

~~NOTE 2: I still need to finish migrating the previously-established styles for "Cooling Centers" (black border around points, smaller point radius, etc)~~

NOTE 3: we still need to categorize / consolidate / choose colors for "Public Housing", so these points are currently not categorized by color. Tooltips for the new layer also need adjustment (currently reusing "Cooling Centers" tooltip, but the column names differ)

Screenshot 2024-07-22 at 4 16 04 PM

## How to Test
1. Navigate to https://deploy-preview-179--chicago-env-explorer.netlify.app/map
    * You should see that the variable "Heat Index (Maximum)" is selected by default
    * You should see that the "Cooling Centers" overlay is enabled by default
2. Enable the new "Public Housing" overlay
    * You should see many more dots appear on the map - these are locations of Public Housing in Chicago
3. Experiment with other past overlays (Historical Redlining, Community Areas, Wards, Industrial or Non-Residential Areas, etc)

### CODE REVIEW

**Comment by mradamcox** [comment]
This is coming along really well, but I've set it to draft because we'll need a bit more completeness before it's ready to merge into main. At the very least, the pop-up should be styled a bit better and should have more info it in (maybe configured as a parameter in the Google Sheet?), and per Note 2 the cooling centers should be styled just like they were before.

At any rate, this is very much on the right track, as far as I'm concerned. Thank you!

**Comment by bodom0015** [comment]
I'm still working on adding dynamic info in the pop-ups... this is a tricky problem, since every type of data point will have a different expected format / columns here. I'm looking into generic patterns that could work for any variable, but haven't quite found one that works yet

**Comment by mradamcox** [comment]
Great, it's looking good. One idea would be a single field that is specified to hold the popup content. Or, perhaps two fields, one for the title and one for the content. These would be two new columns in the Overlays sheet, `popupTitle` and `popupContent` (for example). The columns would hold the name of the fields in the source data to use on the map. There would need to be graceful handling if these aren't provided, though.

**Comment by bodom0015** [comment]
Awesome, I was able to implement this without too much trouble :+1: I changed the name of the CoolingCenter popup to be a bit more generic, and implemented some new logic there:
* `popupTitle` is a template string, so that we are allowed to use variable names in the title (e.g. `{site_type}: {site_name}`)
* `popUpContent` is an array of property names that we want to include in the popup's table body

**Comment by Makosak** [comment]
From my review, recommend the following updates:
- remove the "property type" preface in title, as for now it leads to too long a name, ex. "Senior: G&A Senior Residences at Eastgate Village" becomes "G&A Senior Residences at Eastgate Village"
-  fix the zip code error -- there is a comma added, ex. 60,616
- add "Management" to top row as this may be the most important in policy work, also shortening to "Management" from "Management Company"

Later, we may want to check out:
- Changing the dot size at different zoom levels (see Mapbox documentation)
- Add custom icons

**Comment by bodom0015** [comment]
@mradamcox @Makosak I believe I've addressed most of the feedback here :+1: 

Google Sheet adjustments:
* Public Housing layer now uses green dots instead of black (adjusted google sheet)
* Remove `{site_type}` and `{property_type}` from the popupTitle (adjusted google sheet)
* Moved "Management" to the top of the Public Housing overlay's point popup

Code adjustments:
* Shorten "Management Company" to "Management" (adjusted google sheet + reworked some of the popup code)
* Overlay point hover should now close when clicking an empty part of the map (code only)
* Fixed formatting of the ZIP code - `toLocaleString("en")` was interpreting these as numerical quantities (code only)

Screenshot 2024-07-23 at 5 28 38 PM

Still looking into these more advanced Mapbox features:
* Change cursor style when hovering over a clickable point
* Using custom icons for map points
* Adjusting point size according to zoom level

**Review by mradamcox — APPROVED** [review]
Great, I think it's time to merge this in. Thanks for all your work on it @bodom0015! Some of these tiny little details like the cursor style can be made into separate tickets to be handled later, not a big deal right now.

**Pull request merged**
