### PR TITLE
fix: cleanup/address build warnings

### LINKED ISSUE #189: General maintenance: Cleanup warnings produced during `yarn build`
Running yarn build creates a handful of warnings, and I'd like to get these cleaned up as much as possible. This ticket is just for a first best-effort attempt, so we can knock out some low-hanging fruit. More involved fixes can be written into other tickets if needed.

Simply run `yarn build` and try to address all the warnings, they are mostly eslint warnings, but also a babel package update is needed, as well as caniuse-lite.

### PR DESCRIPTION
**Pull request by bodom0015**
## Problem
There are quite a few warnings that appear when running `yarn build`

Fixes #189

## Approach
* fix: all build warnings
    * ~~NOTE: there is one warning that we have addressed, but the warning has not gone away: `@babel/plugin-proposal-private-property-in-object`~~

## How to Test
1. Checkout this repo locally
2. Run `yarn install` to update, install, and/or prune dependencies
3. Run `yarn build`
    * You should see that the build warnings no longer appear
4. Navigate to the PR preview, to verify that nothing broke as a result of cleaning up these warnings

### CODE REVIEW

**Comment by mradamcox** [comment]
@bodom0015 Great! Almost all warnings are gone, though I was still getting a warning about `@babel/plugin-transform-private-property-in-object`. Maybe worth a look at babel and why it's even in there.

On `yarn start` I was getting `[DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.` though I had to use `yarn start > out.txt` to see it so the console wouldn't erase the message when the server started.

Also, I'd like you to go just a little further here and see if you can remove some of the other dependencies. For example, I believe that the following are not actually used:

- `netlify-cli` (we only use `yarn build` for deployment, so we could even remove the  `netlify-build` script from package.json)
- `matico-charts`
- `react-ga`
- any others? Maybe just look through the dependency warnings that come up with a fresh `yarn install` or `yarn check` and start there.

Thanks!

**Comment by bodom0015** [comment]
@mradamcox I've put in a "fix" for the babel warning

Some of these warnings come from the `create-react-app` / `react-scripts` system.. this is the default build system for apps created using `create-react-app`. We can use `react-scripts eject` to eject from this default build system and get a bit more control over the webpack build process, but this is a **one-way** process. Once we eject, we will be in full control of the build system (for better or worse)

This is where some of the warnings from babel / create-react-app / webpack dev server are coming from, so maybe it's time to explore the eject as an option?

**Comment by bodom0015** [comment]
@mradamcox I believe that I've put in a "fix" for the babel warning, but not sure if this was the correct call.
Can you confirm the warning that you're seeing, since I'm not sure if I see that on my end?

I saw one warning previously that read as follows:
```
One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.

babel-preset-react-app is part of the create-react-app project, which is not maintained anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
go away.
```

So I used `yarn add --dev @babel/plugin-proposal-private-property-in-object`, but this gave a different warning:
```
warning @babel/plugin-proposal-private-property-in-object@7.21.11: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-property-in-object instead.
```

So I added `@babel/plugin-transform-private-property-in-object` instead, but then the original warning came back since it doesn't seem to recognize that this proposal was merged to the ECMAScript standard and simply changed names. So my workaround for now is to add both plugins (for now/temporarily?), so that the original error goes away.

**Comment by mradamcox** [comment]
Thanks @bodom0015, I really appreciate the extra investigation here. I think we may want to eject at some point, but let's not do it right now... It would be good to take stock of the other react-app projects we have and maybe evaluate whether they should be ejected all at once. 

The babel issue was solved for me earlier by just adding the `@babel/plugin-transform-private-property-in-object` to devDependencies, but maybe you have a slightly different environment that kicks the other error off. Sounds like a no-win situation. Let's just leave it for now, and it could be handled later if we do/don't decide to eject. Thank you!

**Review by mradamcox — APPROVED** [review]
All good.

**Comment by bodom0015** [comment]
@mradamcox I removed `react-ga` and `netlify-cli` as requested, but `@maticoapp/matico_charts` yielded an error when running `yarn build`:
```
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve '@visx/responsive' in '/Users/lambert8/workspace/herop/chicago-environment-explorer/src/components/Charts'


error Command failed with exit code 1.
```

**Comment by bodom0015** [comment]
Looking at `yarn check`, it looks like mostly some dependencies are mismatched with our current version of `react`.
Some (like `recharts`) are expecting React 16, while others (like `material-ui`) are expecting React 18
We are currently using React 17 🤔 

This might require a deeper dive into the app to upgrade/sync all of these libraries to use the correct version without breaking any existing functionality

**Comment by mradamcox** [comment]
@bodom0015 Great! Thanks for figuring this out. Let's wait on the react upgrade, something we'll need to do eventually, but maybe we should tackle that if/when we eject from create-react-app.

**Pull request merged**
